# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 
  name: Default

steps:
- task: CmdLine@2
  inputs:
    script: |
      ping baidu.com -n 10000
      echo Write your commands here
      echo Hello world
